
//! Autogenerated weights for `pallet_dao`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-02-02, STEPS: `70`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/node-template
// benchmark
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_dao
// --extrinsic=*
// --steps
// 70
// --repeat
// 20
// --output
// ./pallets/weights/


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_dao`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_dao::WeightInfo for WeightInfo<T> {
	fn benchmark_name() -> Weight {
		(0 as Weight)
	}
	// Storage: Dao Vision (r:1 w:1)
	// Storage: Dao VisionCount (r:1 w:1)
	fn create_vision(_s: u32, ) -> Weight {
		(17_019_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Vision (r:1 w:1)
	// Storage: Dao VisionCount (r:1 w:1)
	fn remove_vision(_s: u32, ) -> Weight {
		(18_426_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Vision (r:1 w:0)
	// Storage: Dao VisionSigner (r:1 w:1)
	fn sign_vision(_s: u32, ) -> Weight {
		(16_754_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dao Vision (r:1 w:0)
	// Storage: Dao VisionSigner (r:1 w:1)
	fn unsign_vision(s: u32, ) -> Weight {
		(17_688_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_000 as Weight).saturating_mul(s as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dao Organization (r:1 w:1)
	// Storage: Dao OrganizationCount (r:1 w:1)
	fn create_organization(s: u32, ) -> Weight {
		(15_675_000 as Weight)
			// Standard Error: 0
			.saturating_add((3_000 as Weight).saturating_mul(s as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Organization (r:1 w:1)
	// Storage: Dao OrganizationCount (r:1 w:1)
	fn dissolve_organization(_s: u32, ) -> Weight {
		(17_111_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Organization (r:1 w:1)
	// Storage: Dao MemberOf (r:1 w:1)
	fn add_members(_s: u32, ) -> Weight {
		(20_260_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Organization (r:1 w:0)
	// Storage: Dao OrganizationTasks (r:1 w:1)
	fn add_tasks(_s: u32, ) -> Weight {
		(18_843_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dao Organization (r:1 w:1)
	// Storage: Dao MemberOf (r:1 w:1)
	fn remove_members(_s: u32, ) -> Weight {
		(23_003_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Organization (r:1 w:0)
	// Storage: Dao OrganizationTasks (r:1 w:1)
	fn remove_tasks(_s: u32, ) -> Weight {
		(19_508_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
