
//! Autogenerated weights for `pallet_dao`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-15, STEPS: `100`, REPEAT: 50, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/node-template
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// *
// --extrinsic
// *
// --steps
// 100
// --repeat
// 50
// --output
// ./runtime/src/weights/


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_dao`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_dao::WeightInfo for WeightInfo<T> {
	// Storage: Dao Vision (r:1 w:1)
	// Storage: Dao VisionCount (r:1 w:1)
	fn create_vision(_s: u32, ) -> Weight {
		(13_947_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Vision (r:1 w:1)
	// Storage: Dao VisionCount (r:1 w:1)
	fn remove_vision(_s: u32, ) -> Weight {
		(15_275_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Vision (r:1 w:0)
	// Storage: Dao ApplicantsToOrganization (r:1 w:1)
	fn sign_vision(_s: u32, ) -> Weight {
		(13_370_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dao Vision (r:1 w:0)
	// Storage: Dao ApplicantsToOrganization (r:1 w:1)
	fn unsign_vision(_s: u32, ) -> Weight {
		(13_991_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dao Organization (r:1 w:1)
	// Storage: Dao OrganizationCount (r:1 w:1)
	fn create_organization(_s: u32, ) -> Weight {
		(12_885_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Organization (r:1 w:1)
	// Storage: Dao OrganizationCount (r:1 w:1)
	fn dissolve_organization(_s: u32, ) -> Weight {
		(13_823_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Organization (r:1 w:1)
	// Storage: Dao MemberOf (r:1 w:1)
	fn add_members(_s: u32, ) -> Weight {
		(16_948_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Organization (r:1 w:0)
	// Storage: Dao OrganizationTasks (r:1 w:1)
	fn add_tasks(_s: u32, ) -> Weight {
		(15_535_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Dao Organization (r:1 w:1)
	// Storage: Dao MemberOf (r:1 w:1)
	fn remove_members(_s: u32, ) -> Weight {
		(19_269_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Dao Organization (r:1 w:0)
	// Storage: Dao OrganizationTasks (r:1 w:1)
	fn remove_tasks(_s: u32, ) -> Weight {
		(15_993_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
