
//! Autogenerated weights for `pallet_profile`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-04-15, STEPS: `100`, REPEAT: 50, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/node-template
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// *
// --extrinsic
// *
// --steps
// 100
// --repeat
// 50
// --output
// ./runtime/src/weights/


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_profile`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_profile::WeightInfo for WeightInfo<T> {
	// Storage: Profile Profiles (r:1 w:1)
	// Storage: Profile ProfileCount (r:1 w:1)
	fn profile_creation(x: u32, _s: u32, ) -> Weight {
		(31_984_000 as Weight)
			// Standard Error: 0
			.saturating_add((4_000 as Weight).saturating_mul(x as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Profile Profiles (r:1 w:1)
	fn profile_update(_s: u32, ) -> Weight {
		(26_136_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Profile Profiles (r:1 w:1)
	// Storage: Profile ProfileCount (r:1 w:1)
	fn profile_remove(_s: u32, ) -> Weight {
		(27_961_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}
